import type { Metadata } from "next";
import "../globals.css";
import { Lexend } from "next/font/google";
const lexend = Lexend({ subsets: ["latin"] });
import { Providers } from "../providers";
import Navbarr from "../../components/Shared/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} bg-[#000000]`}>
        <Providers>
          {" "}
          <Navbarr />
          {children}
        </Providers>
      </body>
    </html>
  );
}
