import type { Metadata } from "next";
import "../globals.css";
import { Lexend } from "next/font/google";
const lexend = Lexend({ subsets: ["latin"] });
import { Providers } from "../providers";
import Navbarr from "../../components/Shared/Navbar";
import RecoilRootWrapper from "@/wrappers/RecoilRootWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RecoilRootWrapper>
      <html
        lang="en"
        style={{ height: "100%", margin: 0, padding: 0, overflow: "hidden" }}
      >
        <body
          className={`${lexend.className} bg-[#000000]`}
          style={{ height: "100%", margin: 0, padding: 0, overflow: "hidden" }}
        >
          <Providers>
            <Navbarr />
            <div className="flex justify-center items-center h-full">
              <div className="onboardbg px-8 rounded-lg shadow-lg w-5/6 text-center">
                {children}
              </div>
            </div>
          </Providers>
        </body>
      </html>
    </RecoilRootWrapper>
  );
}
