import type { Metadata } from "next";
import "../globals.css";
import { Lexend } from "next/font/google";
const lexend = Lexend({ subsets: ["latin"] });
import { Providers } from "../providers";
import Navbarr from "../../components/Shared/Navbar";
import Sidebar from "../../components/Shared/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lexend.className} bg-black`}>
        <Providers>
          <div className="flex flex-col min-h-screen">
            <Navbarr /> {/* Dashboard-specific navbar */}
            <div className="flex flex-grow">
              {/* Sidebar with a fixed width */}
              <div className="flex-shrink-0">
                {" "}
                {/* Ensuring the sidebar does not shrink */}
                <Sidebar />
              </div>
              {/* Main content area with dashboard background */}
              <main className="flex-grow p-6 ml-72">
                {" "}
                {/* Adding margin-left to account for the sidebar's width */}
                <div className="dashboardbg h-full w-full rounded-lg p-3">
                  <div className="h-full overflow-y-auto">{children}</div>
                </div>
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
