import type { Metadata } from "next";
import RecoilRootWrapper from "@/wrappers/RecoilRootWrapper";
import "../globals.css";
import { Lexend } from "next/font/google";
import { Providers } from "../providers";
import Navbarr from "../../components/Shared/Navbar";
import Sidebar2 from "@/components/Shared/Sidebar2";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const lexend = Lexend({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RecoilRootWrapper>
      <html lang="en">
        <body className={`${lexend.className} bg-black`}>
          <Providers>
            <div className="flex flex-col min-h-screen">
              <Navbarr /> {/* Dashboard-specific navbar */}
              <div className="flex flex-grow">
                {/* Sidebar with a fixed width */}
                <div className="w-72">
                  <Sidebar2 />
                </div>
                {/* Main content area with dashboard background */}
                <main className="flex-grow w-full p-6">
                  <div className="dashboardbg h-full ml-10 mr-10 rounded-lg p-3">
                    <div className="h-full text-white overflow-y-auto">
                      {children}
                    </div>
                  </div>
                </main>
              </div>
            </div>
          </Providers>
        </body>
      </html>
    </RecoilRootWrapper>
  );
}
